" Make external commands work through a pipe instead of a pseudo-tty
"set noguipty

" You can also specify a different font, overriding the default font
"if has('gui_gtk2')
"  set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
"else
"  set guifont=-misc-fixed-medium-r-normal--14-130-75-75-c-70-iso8859-1
"endif

" If you want to run gvim with a dark background, try using a different
" colorscheme or running 'gvim -reverse'.
" http://www.cs.cmu.edu/~maverick/VimColorSchemeTest/ has examples and
" downloads for the colorschemes on vim.org

" Source a global configuration file if available
if filereadable("/etc/vim/gvimrc.local")
  source /etc/vim/gvimrc.local
endif

" --> НАСТРОЙКИ ДЛЯ GUI
if has('gui')
    " colorscheme jellybeans
    colorscheme base16-default
    " let g:airline_theme='base16'

    set guifont=Monospace\ 10
    " set guifont=Monofur\ 14
    au VimEnter *  NERDTree

    " Убрать отображение меню
    set guioptions-=m
    " Убрать отображение тулбара
    set guioptions-=T
    " Убрать правый скролбар
    set guioptions-=r
    " Убираем полосы прокрутки слева
    set guioptions-=L
    " Отключаем графические табы (текстовые занимают меньше места)
    set guioptions-=e

    " Цвета табов
    hi TabLineFill guifg=NONE guibg=NONE
    hi TabLine guifg=#c0c0c0 guibg=NONE
    hi TabLineSel guifg=#000000 guibg=#df5f00
    " Цвета statusline
    " hi StatusLine guibg=#404040 guifg=orange

    " При смене раскладки на русскую - сменить цвет курсора
    highlight lCursor guifg=NONE guibg=Cyan
    " Подсветка нумерации
    hi LineNr gui=NONE guifg=#005f5f guibg=NONE

endif

" Размер окна GVIM
"147 - для всего
set lines=41 columns=147

"Ctrl-c to copy in + buffer from visual mode
vmap <C-c> "+y
"Ctrl-p to paste from the + register in cmd mode
map <C-v> "+p
"Ctrl-p to paste from the + register while editing
imap <C-v> <esc><C-v>
